In [2]:
import numpy as np

In [3]:
cil_observado = np.array([1200,2230,1650,1220,2560,900,1480])
consumo_observado = np.array([.06,.1,.11,.05,.1,.07,.11])

In [4]:
regressores = cil_observado.reshape((-1,1))
regressores

array([[1200],
       [2230],
       [1650],
       [1220],
       [2560],
       [ 900],
       [1480]])

In [5]:
features = variaveis_independentes = regressores
alvos = variaveis_dependentes = variaveis_respostas = variaveis_de_desfecho = consumo_observado

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
modelo = LinearRegression().fit(regressores,consumo_observado)

In [8]:
modelo.coef_ # Coeficiente angular do modelo

array([2.62359965e-05])

In [9]:
f'{modelo.coef_[0]:.20f}'

'0.00002623599651170592'

In [10]:
modelo.intercept_

0.043586771315489374

In [11]:
consumo_estimado = modelo.predict(regressores)

In [12]:
consumo_estimado

array([0.07506997, 0.10209304, 0.08687617, 0.07559469, 0.11075092,
       0.06719917, 0.08241605])

In [13]:
erros_lineares = consumo_observado - consumo_estimado

In [14]:
erros_lineares

array([-0.01506997, -0.00209304,  0.02312383, -0.02559469, -0.01075092,
        0.00280083,  0.02758395])

In [15]:
erro_quadratico_medio = np.mean(np.square(erros_lineares))
erro_quadratico_medio

0.0003293694237606495

In [16]:
from sklearn.metrics import mean_squared_error
mean_squared_error(consumo_observado, modelo.predict(regressores))

0.0003293694237606495

In [17]:
cilindradas_das_opcoes_de_compra = np.array([1356,2544])

In [18]:
preditores_de_compra = cilindradas_das_opcoes_de_compra.reshape((-1,1))
preditores_de_compra

array([[1356],
       [2544]])

In [19]:
modelo.predict(preditores_de_compra)

array([0.07916278, 0.11033115])

In [20]:
1/modelo.predict(preditores_de_compra)

array([12.63219871,  9.06362376])